from __future__ import annotations

import argparse
import getpass
import importlib.util
import os
import shutil
import subprocess
import sys
import textwrap
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = PROJECT_ROOT / ".env.local"
TMP_ROOT = PROJECT_ROOT / ".tmp" / "runtime-setup"
VENV_DIR = PROJECT_ROOT / ".uvenv"
VENV_PYTHON = VENV_DIR / "Scripts" / "python.exe"
SAFE_TEMP_ROOT = TMP_ROOT / "safe-python"


@dataclass(slots=True)
class ProbeResult:
    name: str
    python_api_ok: bool
    command_ok: bool
    command_path: str
    notes: list[str]

    @property
    def available(self) -> bool:
        return self.python_api_ok or self.command_ok


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", maxsplit=1)
        values[key.strip()] = value.strip()
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Local runtime overrides for TeamMindHub.",
        "# Generated by: python -m app.cli.runtime_setup",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _temp_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    TMP_ROOT.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    temp_path = str(TMP_ROOT)
    env["TMP"] = temp_path
    env["TEMP"] = temp_path
    if extra:
        env.update(extra)
    return env


def _run_command(
    command: list[str],
    *,
    env: dict[str, str] | None = None,
    timeout: float = 600.0,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        env=env or _temp_env(),
        check=check,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def _safe_python_wrapper(payload: str) -> str:
    return textwrap.dedent(
        f"""
        import os
        import pathlib
        import shutil
        import sys
        import tempfile
        import uuid

        safe_root = pathlib.Path(os.environ["TEAMMINDHUB_SAFE_TEMP"])
        safe_root.mkdir(parents=True, exist_ok=True)

        def _safe_mkdtemp(suffix="", prefix="tmp", dir=None):
            base_dir = pathlib.Path(dir) if dir else safe_root
            base_dir.mkdir(parents=True, exist_ok=True)
            while True:
                candidate = base_dir / f"{{prefix}}{{uuid.uuid4().hex}}{{suffix}}"
                try:
                    candidate.mkdir(parents=True, exist_ok=False)
                    return str(candidate)
                except FileExistsError:
                    continue

        class _SafeTemporaryDirectory:
            def __init__(self, suffix="", prefix="tmp", dir=None, ignore_cleanup_errors=False):
                self.name = _safe_mkdtemp(suffix=suffix, prefix=prefix, dir=dir)
                self.ignore_cleanup_errors = ignore_cleanup_errors

            def __enter__(self):
                return self.name

            def __exit__(self, exc_type, exc, tb):
                shutil.rmtree(self.name, ignore_errors=self.ignore_cleanup_errors or True)
                return False

            def cleanup(self):
                shutil.rmtree(self.name, ignore_errors=True)

        tempfile.mkdtemp = _safe_mkdtemp
        tempfile.TemporaryDirectory = _SafeTemporaryDirectory
        {payload}
        """
    )


def _run_python_with_safe_temp(
    python_path: Path,
    payload: str,
    *args: str,
    timeout: float = 1800.0,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    env = _temp_env({"TEAMMINDHUB_SAFE_TEMP": str(SAFE_TEMP_ROOT)})
    SAFE_TEMP_ROOT.mkdir(parents=True, exist_ok=True)
    return _run_command(
        [str(python_path), "-c", _safe_python_wrapper(payload), *args],
        env=env,
        timeout=timeout,
        check=check,
    )


def _venv_python_candidates() -> Iterable[Path]:
    yield VENV_PYTHON
    yield Path(sys.executable)
    base_executable = getattr(sys, "_base_executable", "")
    if base_executable:
        yield Path(base_executable)
    uv_python_root = Path.home() / "AppData" / "Roaming" / "uv" / "python"
    if uv_python_root.exists():
        for python_path in sorted(uv_python_root.glob("**/python.exe"), reverse=True):
            yield python_path


def _bootstrap_python_candidates() -> Iterable[Path]:
    seen: set[Path] = set()
    raw_candidates: list[Path] = []
    base_executable = getattr(sys, "_base_executable", "")
    if base_executable:
        raw_candidates.append(Path(base_executable))
    raw_candidates.append(Path(sys.executable))
    uv_python_root = Path.home() / "AppData" / "Roaming" / "uv" / "python"
    if uv_python_root.exists():
        raw_candidates.extend(sorted(uv_python_root.glob("**/python.exe"), reverse=True))
    for candidate in raw_candidates:
        try:
            resolved = candidate.resolve()
        except OSError:
            resolved = candidate
        if resolved in seen:
            continue
        seen.add(resolved)
        if candidate.exists():
            yield candidate


def resolve_bootstrap_python() -> Path:
    for candidate in _bootstrap_python_candidates():
        try:
            result = _run_command(
                [str(candidate), "-c", "import sys; print(sys.version_info[:2])"],
                timeout=30.0,
                check=False,
            )
        except Exception:
            continue
        if result.returncode == 0:
            return candidate
    raise RuntimeError("No usable Python interpreter found for .uvenv bootstrap")


def _pip_available(python_path: Path) -> bool:
    if not python_path.exists():
        return False
    try:
        _run_command([str(python_path), "-m", "pip", "--version"], timeout=60.0)
        return True
    except Exception:
        return False


def _bootstrap_pip_with_ensurepip(python_path: Path) -> bool:
    try:
        _run_python_with_safe_temp(
            python_path,
            "import ensurepip; ensurepip.bootstrap(upgrade=True, default_pip=True)",
            timeout=600.0,
        )
        return _pip_available(python_path)
    except Exception:
        return False


def _bootstrap_pip_from_bundle(python_path: Path) -> bool:
    try:
        _run_python_with_safe_temp(
            python_path,
            textwrap.dedent(
                """
                import ensurepip
                import sysconfig
                import zipfile
                from pathlib import Path

                site_packages = Path(sysconfig.get_path("purelib"))
                site_packages.mkdir(parents=True, exist_ok=True)
                bundled_dir = Path(ensurepip.__file__).resolve().parent / "_bundled"
                wheels = sorted(bundled_dir.glob("pip-*.whl"))
                if not wheels:
                    raise RuntimeError("Bundled pip wheel not found")
                with zipfile.ZipFile(wheels[-1]) as archive:
                    archive.extractall(site_packages)
                """
            ),
            timeout=600.0,
        )
        return _pip_available(python_path)
    except Exception:
        return False


def _run_pip(python_path: Path, arguments: list[str], *, timeout: float = 1800.0) -> None:
    if not _pip_available(python_path):
        raise RuntimeError(f"pip is not available in {python_path}")
    _run_python_with_safe_temp(
        python_path,
        "from pip._internal.cli.main import main; raise SystemExit(main(sys.argv[1:]))",
        *arguments,
        timeout=timeout,
    )


def _read_dependency_groups() -> dict[str, list[str]]:
    pyproject_path = PROJECT_ROOT / "pyproject.toml"
    with pyproject_path.open("rb") as handle:
        pyproject_data = tomllib.load(handle)
    project = pyproject_data.get("project", {})
    optional = project.get("optional-dependencies", {})
    return {
        "base": list(project.get("dependencies", [])),
        "dev": list(optional.get("dev", [])),
        "oss": list(optional.get("oss", [])),
    }


def _lightweight_oss_packages(packages: list[str]) -> list[str]:
    heavy_prefixes = ("docling",)
    return [package for package in packages if not package.startswith(heavy_prefixes)]


def ensure_project_venv(recreate: bool = False) -> Path:
    bootstrap_python = resolve_bootstrap_python()
    if recreate and VENV_DIR.exists():
        shutil.rmtree(VENV_DIR, ignore_errors=True)
    if recreate or not VENV_PYTHON.exists():
        _run_command(
            [str(bootstrap_python), "-m", "venv", "--without-pip", str(VENV_DIR)],
            timeout=300.0,
        )
    if not _pip_available(VENV_PYTHON):
        if not _bootstrap_pip_with_ensurepip(VENV_PYTHON) and not _bootstrap_pip_from_bundle(VENV_PYTHON):
            raise RuntimeError("Failed to bootstrap pip into .uvenv")
    _run_pip(
        VENV_PYTHON,
        ["install", "--upgrade", "pip", "setuptools", "wheel", "packaging"],
        timeout=1200.0,
    )
    return VENV_PYTHON


def install_project_dependencies(python_path: Path) -> None:
    dependency_groups = _read_dependency_groups()
    packages = [
        *dependency_groups["base"],
        *dependency_groups["dev"],
        *_lightweight_oss_packages(dependency_groups["oss"]),
    ]
    if not packages:
        return
    _run_pip(
        python_path,
        ["install", "--prefer-binary", *packages],
        timeout=3600.0,
    )


def install_optional_package(python_path: Path, package_name: str) -> None:
    _run_pip(python_path, ["install", "--prefer-binary", package_name], timeout=2400.0)


def _find_python_module(module_name: str) -> bool:
    return importlib.util.find_spec(module_name) is not None


def _probe_module_in_python(python_path: Path, module_name: str) -> bool:
    try:
        result = _run_command(
            [
                str(python_path),
                "-c",
                (
                    "import importlib.util, sys; "
                    f"sys.exit(0 if importlib.util.find_spec('{module_name}') else 1)"
                ),
            ],
            timeout=60.0,
            check=False,
        )
        return result.returncode == 0
    except Exception:
        return False


def _probe_command(command_name: str, preferred_command: str | None = None) -> tuple[bool, str, list[str]]:
    notes: list[str] = []
    candidates: list[str] = []
    if preferred_command:
        candidates.append(preferred_command)
    candidates.extend(
        [
            str(VENV_DIR / "Scripts" / f"{command_name}.exe"),
            str(VENV_DIR / "Scripts" / command_name),
        ]
    )
    which_path = shutil.which(command_name)
    if which_path:
        candidates.append(which_path)
    seen: set[str] = set()
    for candidate in candidates:
        if not candidate or candidate in seen:
            continue
        seen.add(candidate)
        executable = shutil.which(candidate) if os.path.basename(candidate) == candidate else candidate
        if not executable or not Path(executable).exists():
            continue
        try:
            result = _run_command([executable, "--help"], timeout=60.0, check=False)
            if result.returncode == 0:
                return True, executable, notes
            notes.append(f"{executable} returned exit code {result.returncode}")
        except Exception as exc:
            notes.append(f"{executable} probe failed: {exc}")
    return False, "", notes


def probe_docling(python_path: Path, preferred_command: str | None = None) -> ProbeResult:
    python_api_ok = _probe_module_in_python(python_path, "docling")
    command_ok, command_path, notes = _probe_command("docling", preferred_command)
    if not python_api_ok:
        notes.append("Python API not importable in .uvenv")
    return ProbeResult(
        name="docling",
        python_api_ok=python_api_ok,
        command_ok=command_ok,
        command_path=command_path,
        notes=notes,
    )


def probe_mineru(python_path: Path, preferred_command: str | None = None) -> ProbeResult:
    python_api_ok = _probe_module_in_python(python_path, "mineru")
    command_ok, command_path, notes = _probe_command("mineru", preferred_command)
    if not python_api_ok:
        notes.append("Python package not importable in .uvenv")
    return ProbeResult(
        name="mineru",
        python_api_ok=python_api_ok,
        command_ok=command_ok,
        command_path=command_path,
        notes=notes,
    )


def _prompt_yes_no(label: str, default: bool) -> bool:
    suffix = " [Y/n]: " if default else " [y/N]: "
    raw = input(label + suffix).strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes", "1", "true"}


def _prompt_text(label: str, default: str = "") -> str:
    prompt = f"{label}"
    if default:
        prompt += f" [{default}]"
    prompt += ": "
    raw = input(prompt).strip()
    return raw or default


def _prompt_secret(label: str, existing: str = "") -> str:
    suffix = " (leave blank to keep current value)" if existing else ""
    raw = getpass.getpass(f"{label}{suffix}: ").strip()
    return raw or existing


def _normalize_bool(value: bool) -> str:
    return "true" if value else "false"


def build_env_overrides(
    existing: dict[str, str],
    *,
    ragflow_enabled: bool,
    ragflow_base_url: str,
    ragflow_api_key: str,
    docling: ProbeResult,
    mineru_enabled: bool,
    mineru: ProbeResult,
) -> dict[str, str]:
    values = dict(existing)
    values["RAGFLOW_ENABLED"] = _normalize_bool(ragflow_enabled)
    values["RAGFLOW_BASE_URL"] = ragflow_base_url
    values["RAGFLOW_API_KEY"] = ragflow_api_key
    values["DOCLING_ENABLED"] = _normalize_bool(docling.available)
    if docling.command_path:
        values["DOCLING_COMMAND"] = docling.command_path
    values["MINERU_ENABLED"] = _normalize_bool(mineru_enabled and mineru.command_ok)
    if mineru.command_path:
        values["MINERU_COMMAND"] = mineru.command_path
    return values


def _print_probe(result: ProbeResult) -> None:
    print(f"\n[{result.name}]")
    print(f"  python api: {'ok' if result.python_api_ok else 'missing'}")
    print(f"  command:    {result.command_path if result.command_ok else 'missing'}")
    for note in result.notes:
        print(f"  note:       {note}")


def run_interactive_setup(recreate_venv: bool = False) -> int:
    print("TeamMindHub local runtime setup\n")
    python_path = ensure_project_venv(recreate=recreate_venv)
    install_project_dependencies(python_path)

    existing = _read_env_file(ENV_FILE)
    docling = probe_docling(python_path, existing.get("DOCLING_COMMAND"))
    if not docling.available and _prompt_yes_no("Docling is missing. Try installing it now?", True):
        install_optional_package(python_path, "docling")
        docling = probe_docling(python_path, existing.get("DOCLING_COMMAND"))

    mineru = probe_mineru(python_path, existing.get("MINERU_COMMAND"))
    if not mineru.command_ok and _prompt_yes_no("MinerU CLI is missing. Try installing it now?", True):
        install_optional_package(python_path, "mineru")
        mineru = probe_mineru(python_path, existing.get("MINERU_COMMAND"))

    _print_probe(docling)
    _print_probe(mineru)

    current_ragflow_enabled = existing.get("RAGFLOW_ENABLED", "false").lower() == "true"
    ragflow_enabled = _prompt_yes_no("Enable RAGFlow deep parsing?", current_ragflow_enabled)
    ragflow_base_url = existing.get("RAGFLOW_BASE_URL", "http://localhost:9380")
    ragflow_api_key = existing.get("RAGFLOW_API_KEY", "")
    if ragflow_enabled:
        ragflow_base_url = _prompt_text("RAGFlow base URL", ragflow_base_url)
        ragflow_api_key = _prompt_secret("RAGFlow API key", ragflow_api_key)
        if not ragflow_api_key.strip():
            print("RAGFlow API key is empty. RAGFlow will stay disabled.")
            ragflow_enabled = False
    else:
        ragflow_api_key = ""

    mineru_enabled = False
    if mineru.command_ok:
        current_mineru_enabled = existing.get("MINERU_ENABLED", "false").lower() == "true"
        mineru_enabled = _prompt_yes_no("Enable MinerU CLI parsing?", current_mineru_enabled)

    values = build_env_overrides(
        existing,
        ragflow_enabled=ragflow_enabled,
        ragflow_base_url=ragflow_base_url,
        ragflow_api_key=ragflow_api_key,
        docling=docling,
        mineru_enabled=mineru_enabled,
        mineru=mineru,
    )
    _write_env_file(ENV_FILE, values)

    print(f"\nWrote local overrides to: {ENV_FILE}")
    print("\nNext steps:")
    print("  1. Start the app with Docker:  docker compose up --build")
    print("  2. Or start natively:         .\\.uvenv\\Scripts\\python.exe -m uvicorn app.main:app --host 0.0.0.0 --port 8000")
    print("  3. Check health:              http://localhost:8000/health")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Configure and self-check local TeamMindHub runtime integrations.")
    parser.add_argument(
        "--recreate-venv",
        action="store_true",
        help="Recreate .uvenv before installing dependencies.",
    )
    args = parser.parse_args()
    return run_interactive_setup(recreate_venv=args.recreate_venv)


if __name__ == "__main__":
    raise SystemExit(main())
